export const QUOTES: string[] = [
    "Code is like humor. When you have to explain it, it's bad.",
    "First, solve the problem. Then, write the code.",
    "Experience is the name everyone gives to their mistakes.",
    "The best error message is the one that never shows up.",
    "Don't comment bad code — rewrite it.",
    "Make it work, make it right, make it fast.",
    "Simplicity is the soul of efficiency.",
    "Every great developer you know got there by solving problems they were unqualified to solve.",
    "The only way to go fast, is to go well.",
    "Clean code always looks like it was written by someone who cares.",
    "Programming isn't about what you know; it's about what you can figure out.",
    "The most disastrous thing that you can ever learn is your first programming language.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "Talk is cheap. Show me the code.",
    "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.",
    "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.",
    "Code never lies, comments sometimes do.",
    "Deleted code is debugged code.",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
    "The best time to plant a tree was 20 years ago. The second best time is now. Same with refactoring.",
    "A ship in port is safe, but that's not what ships are built for. Ship your code!",
    "You're doing great! One commit at a time. 💪",
    "Take breaks. Your brain solves problems while you rest.",
    "Stay curious. Every bug is a lesson in disguise.",
    "You've got this! Keep pushing forward. 🚀",
    "Remember: even senior devs Google things constantly.",
    "Progress, not perfection.",
    "Your future self will thank you for this clean code.",
    "Small steps still move you forward.",
    "Debug with patience, code with passion. 🔥"
];
